### ISSUE TITLE
The task title is always editable even if it is categorized as complete.

### ISSUE THREAD

**Issue by ThierryRakotomanana** [ThierryRakotomanana/kanban-js#5]
#### Description
After creating a task, if you edit the title or details of the task and then click on the "complete" button without clicking on the "edit" button again, the task title remains editable even after the task has been moved to the "complete" status.

#### Screenshots
![The task title when edit is click](https://github.com/ThierryRakotomanana/kanban-js/assets/105288252/72158f9d-4f3a-416e-b3d2-78eb27a338ad)
![after when you click on button complete](https://github.com/ThierryRakotomanana/kanban-js/assets/105288252/820aaa4a-a316-44f6-a9d6-2394dc5309c4)

#### The causes of these bugs
These bugs occur because the "hidden" property is not being applied to the textarea.
```
textarea.hidden {
    display: none;
}
```
#### Tasks
This may help you to fix these bugs , it's just suggestion but if you find better code.

In the `app.js` file, in the function `moveToComplete` 
```javascript
const moveToComplete = (ev) => {
```
- [ ] Check if `textarea` has `hidden` in its `classList`
  - [ ] Use `ev.currentTarget` to traverse the DOM and locate the `textarea` element
  - [ ] Check if it has the class `hidden` using `Element.classList.contains('hidden')`
- [ ] Add `hidden` to `classList` if it's not hidden

**Comment by ekkaaditya200** [comment]
Hey I want to try this, can i get it assigned

**Comment by ThierryRakotomanana** [comment]
Yes, of course, you can work on it @ekkaaditya200
